[features]
seeds = false
[programs.localnet]
auction = "4J6TANDgNiDQFdRuHHoU6qbwoGZo3638w1UXXaEUxspy"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/marcinv/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
